### ISSUE TITLE
option to size images for each screen

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/Slideset#11]
Besides the option to change the amount of images shown on small, medium, large, .. -screen, it would be nice to resize images (in percentage) for each screen as well.

**Comment by C-Lodder** [comment]
This already happens. If you don't add values for small, medium, large and xlarge, the images will scale down instead. I will add an option to enable/disable this so it's clearer.. Thanks

**Comment by betteryouthanme** [comment]
Okay it is not working with Purity III template (T3 Framework)
Protostar works fine

**Comment by C-Lodder** [comment]
Ok thanks :) I'll download/install Purity lll tomorrow and test

**Comment by C-Lodder** [comment]
Fixed for Purity lll: https://github.com/JoomJunk/Slideset/commit/93d7cbbf0a12d92ba56fbcc2f5aac03a6c6d0cea

**Comment by betteryouthanme** [comment]
updated the uikit.min.css file but resizing still does not work for Purity

**Comment by C-Lodder** [comment]
Hmm odd cause it worked fine for me. Let me retest tomorrow and see

**Comment by C-Lodder** [comment]
@betteryouthanme - I've released a 2nd Beta for the Slideset: https://github.com/JoomJunk/Slideset/releases

**Comment by betteryouthanme** [comment]
works all so far but not the image resize :) Using clean installation of latest Joomla3, Purity III 1.1.3 and T3 Framework 2.4.8
![slideset1](https://cloud.githubusercontent.com/assets/8537297/7380931/37478cf8-edff-11e4-8db8-8af9f9f2a9f1.jpg)
![slideset2](https://cloud.githubusercontent.com/assets/8537297/7380933/3b56642c-edff-11e4-9465-35c3d304458c.jpg)

**Comment by C-Lodder** [comment]
Ahh ok you have 1 big image there. About to release a Shoutbox update then go to bed, so I'll fix this tomorrow morning. Once fixed, would you deem the module stable for release (1.0.0)?

**Comment by betteryouthanme** [comment]
Yes absolutely

**Comment by C-Lodder** [comment]
@betteryouthanme - All fixed now:  https://github.com/JoomJunk/Slideset/commit/0c0defba3195695d773e8825c57db17f92e65d64

**Comment by betteryouthanme** [comment]
yes works fine now
